#! /bin/bash

case $1 in
     "smile")
       echo ":)"
       ;;
     "sad")
       echo ":("
       ;;
      "laugh")
        echo ":D"
        ;;
      *)
        echo "I dont konw it yet" 
        ;;
esac
